---
apiVersion: v1
kind: Service
metadata:
  name: subs-apiservice
  namespace: netsubs
spec:
  type: NodePort
  selector:
    app: subs-apiservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30005
