name: .NET Core Unit Tests

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: |
          cd NetSubs.ApiService
          dotnet restore NetSubs.ApiService.sln

      - name: Build solution
        run: |
          cd NetSubs.ApiService
          dotnet build --no-restore --configuration Release NetSubs.ApiService.sln

      - name: Run unit tests
        run: |
          cd NetSubs.ApiService/Tests/UnitTests
          dotnet test --no-build --verbosity normal
