name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Устанавливаем требуемую версию .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      # Восстанавливаем NuGet-пакеты
      - name: Restore dependencies
        run: dotnet restore
        
      # Собираем проект целиком
      - name: Build solution
        run: dotnet build --configuration Release
        
      # Запускаем юнит-тесты
      - name: Run unit tests
        run: |
          dotnet test --no-build --logger "trx;LogFileName=test_results.trx" NetSubs.ApiService/Tests/UnitTests
